/**
 * Writes dist/_headers after the build.
 *
 * The CSP is generated rather than hand-written because this site ships inline scripts on purpose:
 * the theme bootstrap has to run before first paint, and it is built from PALETTE so it cannot
 * drift from tokens.css. Externalising it would trade a guarantee for a round trip, and hard-coding
 * its hash would rot the first time the palette changes.
 *
 * So the hashes are read back out of the HTML that was actually built. A script that ships is a
 * script that is hashed, by construction — the failure mode where the policy and the page disagree
 * cannot occur.
 *
 * `application/ld+json` is skipped: it is a data block the browser never executes, so CSP does not
 * gate it. Speculation rules are hashed like any other inline script — the `'inline-speculation-rules'`
 * keyword cannot be used here, because CSP ignores the unsafe-inline family entirely once a policy
 * carries any hash, and this one does.
 */

import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const DIST = path.join(process.cwd(), "dist");
const INLINE_SCRIPT = /<script(?![^>]*\bsrc=)([^>]*)>([\s\S]*?)<\/script>/g;
const TYPE_ATTR = /\btype=["']([^"']+)["']/;
const SKIPPED_TYPES = new Set(["application/ld+json"]);

function htmlFiles(dir) {
  return readdirSync(dir).flatMap((name) => {
    const child = path.join(dir, name);
    if (statSync(child).isDirectory()) return htmlFiles(child);
    return child.endsWith(".html") ? [child] : [];
  });
}

function inlineScriptHashes() {
  const hashes = new Set();

  for (const file of htmlFiles(DIST)) {
    const html = readFileSync(file, "utf8");
    for (const [, attrs, body] of html.matchAll(INLINE_SCRIPT)) {
      const type = attrs.match(TYPE_ATTR)?.[1];
      if (type && SKIPPED_TYPES.has(type)) continue;
      if (body.trim() === "") continue;
      hashes.add(`'sha256-${createHash("sha256").update(body, "utf8").digest("base64")}'`);
    }
  }

  return [...hashes].sort();
}

const scriptSources = ["'self'", ...inlineScriptHashes()];

const policy = [
  "default-src 'self'",
  "img-src 'self' data:",
  // Layout sets custom properties through style attributes, which style-src governs.
  "style-src 'self' 'unsafe-inline'",
  "font-src 'self'",
  // The only request the site makes is /cdn-cgi/trace, which is same-origin.
  "connect-src 'self'",
  `script-src ${scriptSources.join(" ")}`,
  "object-src 'none'",
  "base-uri 'self'",
  "frame-ancestors 'none'",
  "form-action 'self'",
].join("; ");

const headers = `# Generated by scripts/build-headers.mjs — edit that, not this.
/*
  Content-Security-Policy: ${policy}
  Referrer-Policy: no-referrer
  X-Content-Type-Options: nosniff
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), serial=(), bluetooth=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  X-Frame-Options: DENY
/_astro/*
  Cache-Control: public, max-age=31536000, immutable
/fonts/*
  Cache-Control: public, max-age=31536000, immutable
`;

writeFileSync(path.join(DIST, "_headers"), headers, "utf8");
console.log(`dist/_headers written; ${scriptSources.length - 1} inline script hashes`);
