/**
 * Self-host the site fonts (fixes the render-blocking Google Fonts CSS).
 * RUN LOCALLY (needs open internet):  node scripts/fetch-fonts.mjs
 *
 * What it does:
 *  1. Fetches the Google Fonts CSS with a modern-Chrome UA (=> woff2, latin subsets)
 *  2. Downloads every referenced woff2 into public/fonts/
 *  3. Writes src/styles/fonts.css with same-origin @font-face rules
 *  4. Rewrites Layout.astro: Google <link>s -> local preload + imported stylesheet
 * Re-runnable; idempotent.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,300..800&family=JetBrains+Mono:wght@400;500;700&display=swap";
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

const css = await (
  await fetch(CSS_URL, { headers: { "user-agent": UA } })
).text();

await mkdir(join(ROOT, "public/fonts"), { recursive: true });

let localCss =
  "/* generated by scripts/fetch-fonts.mjs - do not edit by hand */\n";
const seen = new Map();
// keep only latin blocks (the site is English); grab each @font-face
for (const block of css.split("@font-face").slice(1)) {
  if (!/unicode-range:[^;]*U\+0000/.test(block)) continue; // latin only
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;
  let name = seen.get(url);
  if (!name) {
    name = `${url.split("/").slice(-2).join("-")}`.replace(/[^a-z0-9.-]/gi, "");
    seen.set(url, name);
    const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
    await writeFile(join(ROOT, "public/fonts", name), buf);
    console.log("saved", name, `${(buf.length / 1024).toFixed(1)}kb`);
  }
  localCss +=
    "@font-face" + block.replace(url, `/fonts/${name}`).trimEnd() + "\n";
}
await writeFile(join(ROOT, "src/styles/fonts.css"), localCss);
console.log("wrote src/styles/fonts.css referencing", seen.size, "files");

// patch Layout.astro
const layoutPath = join(ROOT, "src/layouts/Layout.astro");
let layout = await readFile(layoutPath, "utf8");
const googleBlock =
  /\s*<link rel="preconnect" href="https:\/\/fonts\.googleapis\.com" \/>[\s\S]*?rel="stylesheet"\s*\/>/;
if (googleBlock.test(layout)) {
  const preloads = [...seen.values()]
    .slice(0, 2) // the two most critical files; the rest arrive via fonts.css
    .map(
      (n) =>
        `    <link rel="preload" href="/fonts/${n}" as="font" type="font/woff2" crossorigin />`,
    )
    .join("\n");
  layout = layout.replace(
    googleBlock,
    `\n    <!-- self-hosted fonts (scripts/fetch-fonts.mjs) -->\n${preloads}`,
  );
  if (!layout.includes("@/styles/fonts.css")) {
    layout = layout.replace(
      'import "@/styles/main.css";',
      'import "@/styles/main.css";\nimport "@/styles/fonts.css";',
    );
  }
  await writeFile(layoutPath, layout);
  console.log("Layout.astro rewritten - Google Fonts CDN removed");
} else {
  console.log("Layout.astro already self-hosted - nothing to patch");
}
console.log("\nDone. Rebuild with: pnpm build");
